apiVersion : v1
kind : Pod
metadata:
  name : test-configmap
  namespace : production

spec :
  containers:
  - name : busybox
    image : busybox
    command : 
    - /bin/sh
    - -c
    - sleep 3600
    volumeMounts:
    - name : config
      mountPath: /app/config

  volumes: 
  - name : config
    configMap:
      name : backend-config