apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: production
spec:
    replicas: 3
    selector:
      matchLabels:
        app: frontend
    template:
      metadata:
        labels:
          app: frontend
      spec:
        containers:
        - name: frontend
          image: smsohag/frontend:c1a59b8
          ports:
          - containerPort: 80
            name: frontend
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi" 
            limits:
              cpu: "500"
              memory: "512Mi"
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: frontend
                topologyKey: kubernetes.io/hostname