apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    app.kubernetes.io/managed-by: Helm

  annotations:
    meta.helm.sh/release-name: production
    meta.helm.sh/release-namespace: production

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      affinity:
        {{- toYaml .Values.backend.affinity | nindent 8 }}

      containers:
        - name: backend

          image: {{ .Values.backend.image.repository }}:a2f2630

          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - name: backend
              containerPort: {{ .Values.backend.port }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: backend-config

            - secretRef:
                name: backend-secret

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}