apiVersion: v1
kind: Secret
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace}}
data:
  APP_ENV: {{ .Values.backend.config.appEnv}}
  DB_HOST: {{ .Values.backend.config.dbHost}}
  DB_PORT: {{ .Values.backend.config.dbPort}}