apiVersion: v1
kind: Service
metadata:
  name : backend
  namespace: {{ .Release.Namespace }}
  labels:
    app: backend
    app.kubernetes.io/managed-by: Helm

  annotations:
    meta.helm.sh/release-name: production
    meta.helm.sh/release-namespace: production
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: backend
  ports:
    - name: backend
      port: {{ .Values.backend.service.port}}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP