apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: {{ .Release.Namespace}}
data:
  APP_ENV: {{ .Values.backend.config.appEnv | quote }}
  DB_HOST: {{ .Values.backend.config.dbHost | quote }}
  DB_PORT: {{ .Values.backend.config.dbPort | quote }}