apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount}}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository}}:{{ .Values.frontend.image.tag}}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy}}
          ports:
            - name: frontend
              containerPort: {{ .Values.frontend.port}}
          resources: 
            {{- toYaml .Values.frontend.resources | nindent 12 }}
                volumeMounts:
        - name: frontend-config
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
          readOnly: true
          
      affinity:
        {{- toYaml .Values.frontend.affinity | nindent 8 }}

      volumes:
      - name: frontend-config
        configMap:
          name: frontend-config