apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace}}
  labels:
    app: frontend
    app.kubernetes.io/managed-by: Helm

  annotations:
    meta.helm.sh/release-name: production
    meta.helm.sh/release-namespace: production
spec:
  type: {{ .Values.frontend.service.type}}
  selector:
    app: frontend
  ports:
    - name: frontend
      port: {{ .Values.frontend.service.port}}
      targetPort: {{ .Values.frontend.service.targetPort}}
      protocol: TCP