apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Release.Namespace}}
data:
  config.js: |
    window.APP_CONFIG = {
      API_URL: {{ .Values.frontend.config.apiUrl | quote  }}
    };