apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Release.Namespace}}
spec:
  type: {{ .Values.frontend.type}}
  selector:
    matchLabels: frontend
    ports:
        - name: frontend
          port: {{ .Values.frontend.service.port}}
          targetPort: {{ .Values.frontend.service.targetPort}}
          protocol: TCP