apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: {{ .Release.Namespace}}
data:
  MYSQL_DATABASE: {{ .Values.mysql.config.database | quote }}
  MYSQL_HOST: mysql
  MYSQL_PORT: {{ .Values.mysql.port | quote }}