- name: Configure worker servers
  hosts: workers
  become: true

  tasks:
    - name: Insure Curl is install
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Load Kubernetes kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Persist Kubernetes kernel modules
      ansible.builtin.copy:
        dest: /etc/modules-load.d/kubernetes.conf
        content: |
          overlay
          br_netfilter
        mode: '0644'
      




