- name: Configure worker servers
  hosts: workers
  become: true

  tasks:
    - name: Insure Curl is install
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Ensure Ansible test directory exists
      ansible.builtin.file:
        path: /opt/ansible-test
        state: directory
        mode: '0755'

    




