backend:
  replicaCount: 1

  image:
    tag: a2f2630

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  ingress:
    host: api-staging.sohag.com.bd


frontend:
  replicaCount: 1

  image:
    tag: 1c71ee7

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  ingress:
    host: staging.sohag.com.bd