backend:
  image:
    repository: smsohag/backend
    pullPolicy: IfNotPresent

  port: 5000

  config:
    appEnv: Production
    dbHost: mysql
    dbPort: "3306"



  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000

  ingress:
    enabled: true
    className: nginx
    path: /
    pathType: Prefix


frontend:
  image:
    repository: smsohag/frontend
    pullPolicy: IfNotPresent

  port: 80

  service:
    type: ClusterIP
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    className: nginx
    path: /
    pathType: Prefix

mysql:
  port: 3306

  config:
    database: production
  image:
    repository: mysql
    tag: "8.4"
    pullPolicy: IfNotPresent

  replicaCount: 1

  service:
    type: ClusterIP
    port: 3306

  persistence:
    enabled: true
    size: 5Gi
    accessMode: ReadWriteOnce
    storageClass: local-path

  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"