backend:
  replicaCount: 4

  image:
    repository: smsohag/backend
    tag: a2f2630
    pullPolicy: IfNotPresent

  port: 5000

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: backend
            topologyKey: kubernetes.io/hostname
            
  service:
    type: ClusterIP
    port: 5000
    targetPort: 5000