backend:
  replicaCount: 3
  image:
    tag: 1a75ad3
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  config:
    appEnv: Staging
    dbHost: mysql
    dbPort: "3306"
  ingress:
    host: api-staging.sohag.com.bd
frontend:
  replicaCount: 2
  image:
    tag: c09f008
  config:
    apiUrl: https://api-staging.sohag.com.bd
  resources:
    requests:
      cpu: "50m"
      memory: "128Mi"
    limits:
      cpu: "110m"
      memory: "256Mi"
  ingress:
    host: staging.sohag.com.bd
